# This file was auto-generated by Fern from our API Definition.

import typing

StartAgentsRequestPropertiesAsrVendor = typing.Union[
    typing.Literal[
        "fengming", "tencent", "microsoft", "xfyun", "xfyun_bigmodel", "xfyun_dialect"
    ],
    typing.Any,
]
