# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .bytedance_duplex_tts_params import BytedanceDuplexTtsParams
from .bytedance_tts_params import BytedanceTtsParams
from .cosyvoice_tts_params import CosyvoiceTtsParams
from .microsoft_tts_params import MicrosoftTtsParams
from .minimax_tts_params import MinimaxTtsParams
from .stepfun_tts_params import StepfunTtsParams
from .tencent_tts_params import TencentTtsParams


class Tts_Minimax(UncheckedBaseModel):
    vendor: typing.Literal["minimax"] = "minimax"
    params: MinimaxTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tts_Tencent(UncheckedBaseModel):
    vendor: typing.Literal["tencent"] = "tencent"
    params: TencentTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tts_Bytedance(UncheckedBaseModel):
    vendor: typing.Literal["bytedance"] = "bytedance"
    params: BytedanceTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tts_Microsoft(UncheckedBaseModel):
    vendor: typing.Literal["microsoft"] = "microsoft"
    params: MicrosoftTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tts_Cosyvoice(UncheckedBaseModel):
    vendor: typing.Literal["cosyvoice"] = "cosyvoice"
    params: CosyvoiceTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tts_BytedanceDuplex(UncheckedBaseModel):
    vendor: typing.Literal["bytedance_duplex"] = "bytedance_duplex"
    params: BytedanceDuplexTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tts_Stepfun(UncheckedBaseModel):
    vendor: typing.Literal["stepfun"] = "stepfun"
    params: StepfunTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Tts = typing_extensions.Annotated[
    typing.Union[
        Tts_Minimax,
        Tts_Tencent,
        Tts_Bytedance,
        Tts_Microsoft,
        Tts_Cosyvoice,
        Tts_BytedanceDuplex,
        Tts_Stepfun,
    ],
    UnionMetadata(discriminant="vendor"),
]
